# Generated by Django 4.2.1 on 2024-07-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alumnos_profesores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
