# Generated by Django 4.2.1 on 2024-07-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_alumnos_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('duracion', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesores',
            name='apellido',
            field=models.CharField(default='apellido', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesores',
            name='curso',
            field=models.CharField(default='curso', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='apellido',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
