# Generated by Django 4.2.1 on 2024-08-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=20)),
                ('rubro', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('proyectos', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('carrera', models.CharField(max_length=40)),
                ('salario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionesAcademicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('agencia', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
